import { readFileSync, existsSync } from 'fs';
import { parse, type DocumentNode, type FragmentDefinitionNode, type FieldNode, type SelectionNode, type InlineFragmentNode } from 'graphql';
import { findGraphqlFiles } from './graphql-file-parser';

export interface ParsedFragment {
	name: string;
	typeCondition: string;
	fields: string[];
	inlineFragments: string[];
	document: string;
	filePath: string;
}

export function parseFragmentFile(filePath: string): ParsedFragment[] | null {
	if (!existsSync(filePath)) return null;

	const content = readFileSync(filePath, 'utf-8').trim();
	if (!content) return null;

	let doc: DocumentNode;
	try {
		doc = parse(content);
	} catch {
		return null;
	}

	const fragments: ParsedFragment[] = [];

	for (const def of doc.definitions) {
		if (def.kind !== 'FragmentDefinition') continue;
		const f = def as FragmentDefinitionNode;
		const name = f.name?.value;
		if (!name) continue;

		const fields: string[] = [];
		const inlineFragments: string[] = [];

		for (const sel of f.selectionSet.selections) {
			collectFieldInfo(sel, fields, inlineFragments);
		}

		fragments.push({
			name,
			typeCondition: f.typeCondition.name.value,
			fields,
			inlineFragments,
			document: content,
			filePath,
		});
	}

	return fragments.length > 0 ? fragments : null;
}

function collectFieldInfo(sel: SelectionNode, fields: string[], inlineFragments: string[]): void {
	if (sel.kind === 'Field') {
		const f = sel as FieldNode;
		if (f.name.value.startsWith('__')) return;
		fields.push(f.name.value);
	} else if (sel.kind === 'InlineFragment') {
		const inf = sel as InlineFragmentNode;
		if (inf.typeCondition) {
			inlineFragments.push(inf.typeCondition.name.value);
		}
		for (const s of inf.selectionSet.selections) {
			collectFieldInfo(s, fields, inlineFragments);
		}
	} else if (sel.kind === 'FragmentSpread') {
		// referenced by name — caller can resolve separately
	}
}

export function generateFragmentCode(
	fragments: ParsedFragment[],
	typesCode?: string,
	clientPreset?: boolean,
): string {
	const lines: string[] = [
		'// Auto-generated by @dumbql/codegen. DO NOT EDIT.\n',
	];

	if (clientPreset) {
		lines.push('import { createTypedQuery, type TypedQueryString } from "@dumbql/core";\n');
	} else {
		lines.push('import { gql, type TypedDocumentNode } from "@dumbql/core";\n');
	}

	const typeNames = typesCode
		? extractTypeNames(typesCode)
		: [];

	if (typeNames.length > 0) {
		lines.push('import type {');
		typeNames.forEach((t) => lines.push(`  ${t},`));
		lines.push('} from "../types";\n');
	}

	for (const f of fragments) {
		const resultName = `${f.name}Fragment`;
		const typeName = f.typeCondition;

		lines.push(`export type ${resultName} = Pick<${typeName}, '${f.fields.join("' | '")}'>;`);
		lines.push('');

		const hasInline = f.inlineFragments.length > 0;
		if (hasInline) {
			lines.push(`export type ${resultName}WithInline = ${resultName} & (`);
			lines.push(f.inlineFragments.map((t) => `  { __typename: '${t}' } & Pick<${t}, 'TODO'>`).join(' | '));
			lines.push(');');
			lines.push('');
		}

		const docStr = f.document.replace(/`/g, '\\`').replace(/\$/g, '\\$');

		if (clientPreset) {
			lines.push(`export const ${f.name}: TypedQueryString<${resultName}, Record<string, never>> =`);
			lines.push(`  createTypedQuery<${resultName}, Record<string, never>>(\`${docStr}\`);`);
		} else {
			lines.push(`export const ${f.name}: TypedDocumentNode<${resultName}, Record<string, never>> =`);
			lines.push(`  gql\`${docStr}\` as TypedDocumentNode<${resultName}, Record<string, never>>;`);
		}
		lines.push('');
	}

	return lines.join('\n');
}

export function generateFragmentIndex(fragments: ParsedFragment[]): string {
	const lines: string[] = [
		'// Auto-generated by @dumbql/codegen. DO NOT EDIT.\n',
	];
	for (const f of fragments) {
		lines.push(`export { ${f.name}Fragment, ${f.name} } from "./${f.name}";`);
	}
	return lines.join('\n');
}

function extractTypeNames(code: string): string[] {
	const names = new Set<string>();
	const re = /^export\s+(interface|type|const enum|enum)\s+(\w+)/gm;
	let m;
	while ((m = re.exec(code)) !== null) names.add(m[2]);
	return Array.from(names).sort();
}
