import { readFileSync, existsSync } from 'fs';
import { join, resolve } from 'path';
import { globSync } from 'glob';
import { parse, type DocumentNode, type OperationDefinitionNode, type VariableDefinitionNode } from 'graphql';

export interface OperationVar {
	name: string;
	type: string;
}

export interface ParsedOperation {
	name: string;
	type: 'query' | 'mutation' | 'subscription';
	variables: OperationVar[];
	document: string;
	filePath: string;
}

export function findGraphqlFiles(pattern: string): string[] {
	return globSync(pattern, { absolute: true });
}

export function parseGraphqlFile(filePath: string): ParsedOperation | null {
	if (!existsSync(filePath)) return null;

	const content = readFileSync(filePath, 'utf-8').trim();
	if (!content) return null;

	let doc: DocumentNode;
	try {
		doc = parse(content);
	} catch {
		return null;
	}

	const def = doc.definitions.find(
		(d): d is OperationDefinitionNode => d.kind === 'OperationDefinition',
	);

	if (!def) return null;

	const name = def.name?.value;
	if (!name) return null;

	const variables: OperationVar[] = (def.variableDefinitions || []).map(
		(v: VariableDefinitionNode) => {
			return {
				name: v.variable.name.value,
				type: printTypeRef(v.type),
			};
		},
	);

	return {
		name,
		type: def.operation as 'query' | 'mutation' | 'subscription',
		variables,
		document: content,
		filePath,
	};
}

function printTypeRef(type: unknown): string {
	const wrap = (t: Record<string, unknown> | null): string => {
		if (!t) return '';
		if (t.kind === 'NonNullType') return `${wrap(t.type as Record<string, unknown>)}!`;
		if (t.kind === 'ListType') return `[${wrap(t.type as Record<string, unknown>)}]`;
		return (t.name as { value: string })?.value ?? '';
	};
	return wrap(type as Record<string, unknown>);
}

/** Extract type/interface/enum names from generated TS code */
function extractTypeNames(code: string): string[] {
	const names = new Set<string>();
	const re = /^export\s+(interface|type|const enum|enum)\s+(\w+)/gm;
	let m;
	while ((m = re.exec(code)) !== null) names.add(m[2]);
	return Array.from(names).sort();
}

export function generateTypedDocumentsCode(
	operations: ParsedOperation[],
	schemaTypes?: string[] | string,
	prefix?: string,
	suffix?: string,
): string {
	const typeNames = Array.isArray(schemaTypes)
		? schemaTypes
		: schemaTypes
			? extractTypeNames(schemaTypes)
			: [];

	const lines: string[] = [
		'// Auto-generated by @dumbql/codegen. DO NOT EDIT.\n',
		'import { gql, type TypedDocumentNode } from "@dumbql/core";\n',
	];

	if (typeNames.length > 0) {
		lines.push('import type {');
		typeNames.forEach((t) => lines.push(`  ${t},`));
		lines.push('} from "../types";\n');
	}

	for (const op of operations) {
		const resultName = `${prefix ?? ''}${op.name}${suffix ?? ''}`;
		const varName = `${op.name}Variables`;
		const hasVars = op.variables.length > 0;

		if (hasVars) {
			lines.push(`export interface ${varName} {`);
			for (const v of op.variables) {
				lines.push(`  ${v.name}: ${v.type};`);
			}
			lines.push('}\n');
		}

		const varGeneric = hasVars ? varName : 'Record<string, never>';
		lines.push(`export const ${op.name}: TypedDocumentNode<${resultName}, ${varGeneric}> =`);
		lines.push(`  gql\`${op.document}\` as TypedDocumentNode<${resultName}, ${varGeneric}>;`);
		lines.push('');
	}

	return lines.join('\n');
}

export function generateIndexCode(operations: ParsedOperation[]): string {
	const lines: string[] = [
		'// Auto-generated by @dumbql/codegen. DO NOT EDIT.\n',
	];

	for (const op of operations) {
		lines.push(`export { ${op.name} } from "./${op.name}";`);
	}

	return lines.join('\n');
}
