// Auto-generated by DumbQL. DO NOT EDIT.

export const enum NoteType {
  NOTE = 'NOTE',
  PASSWORD = 'PASSWORD',
}

export interface CreateNoteInput {
  title: string;
  content: string;
  description: string | null | undefined;
  icon: File | null | undefined;
  noteType: NoteType;
}

export interface CreateUserInput {
  username: string;
  password: string;
}

export interface UpdateNoteInput {
  title: string | null | undefined;
  content: string | null | undefined;
  description: string | null | undefined;
  icon: File | null | undefined;
  noteType: NoteType;
}

export interface UpdateUserInput {
  username: string | null | undefined;
  password: string | null | undefined;
  masterKey: string | null | undefined;
}

export interface Mutation {
  createUser: User;
  updateUser: User;
  deleteUser: boolean;
  setMasterKey: User;
  createNote: Note;
  updateNote: Note;
  deleteNote: boolean;
}

export interface Note {
  id: string;
  title: string;
  content: string;
  iconUrl: string | null | undefined;
  description: string | null | undefined;
  noteType: NoteType;
  createdAt: string;
  updatedAt: string | null | undefined;
  author: User;
}

export interface Query {
  getCurrentUser: User;
  getNotes: Note[];
  getNoteDetails: Note;
}

export interface User {
  id: string;
  username: string;
  password: string;
  masterKey: string;
  createdAt: string;
  updatedAt: string;
}
