import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, resolve } from 'path';
import { loadConfig } from './load-config.mjs';

const builtinTypes = new Set([
	'String', 'Int', 'Float', 'Boolean', 'ID',
	'__Schema', '__Type', '__TypeKind', '__Field', '__InputValue',
	'__EnumValue', '__Directive', '__DirectiveLocation',
]);

function resolveRef(typeRef) {
	let current = typeRef;
	let nullable = true;
	let list = false;
	while (current.ofType) {
		if (current.kind === 'NON_NULL') nullable = false;
		if (current.kind === 'LIST') list = true;
		current = current.ofType;
	}
	return { base: current.name, nullable, list };
}

function toTsType(typeRef, scalars) {
	if (!typeRef) return 'unknown';
	const { base, nullable, list } = resolveRef(typeRef);
	if (builtinTypes.has(base)) {
		const mapping = { String: 'string', Int: 'number', Float: 'number', Boolean: 'boolean', ID: 'string' };
		let ts = mapping[base] || scalars[base] || base;
		if (list) ts = `${ts}[]`;
		return nullable ? `${ts} | null | undefined` : ts;
	}
	let ts = scalars[base] || base;
	if (list) ts = `${ts}[]`;
	return nullable ? `${ts} | null | undefined` : ts;
}

function isBuiltin(name) {
	return builtinTypes.has(name) || name.startsWith('__');
}

function generate(schemaData, config) {
	const types = config.codegen?.types ?? config.types ?? {};
	const scalars = types.scalars || {};
	const enumsAsTypes = types.enumsAsTypes ?? false;
	const allTypes = schemaData.types.filter((t) => !isBuiltin(t.name));
	const lines = ['// Auto-generated by DumbQL. DO NOT EDIT.\n'];

	for (const t of allTypes) {
		if (t.kind !== 'ENUM') continue;
		if (enumsAsTypes) {
			lines.push(`export type ${t.name} =`);
			for (const v of t.enumValues) lines.push(`  | '${v.name}'`);
			lines.push(';');
		} else {
			lines.push(`export const enum ${t.name} {`);
			for (const v of t.enumValues) lines.push(`  ${v.name} = '${v.name}',`);
			lines.push('}');
		}
		lines.push('');
	}

	for (const t of allTypes) {
		if (t.kind !== 'INPUT_OBJECT') continue;
		lines.push(`export interface ${t.name} {`);
		for (const f of t.inputFields || []) {
			const ts = toTsType(f.type, scalars);
			lines.push(`  ${f.name}: ${ts};`);
		}
		lines.push('}');
		lines.push('');
	}

	for (const t of allTypes) {
		if (t.kind !== 'OBJECT' && t.kind !== 'INTERFACE') continue;
		lines.push(`export interface ${t.name} {`);
		for (const f of t.fields || []) {
			const ts = toTsType(f.type, scalars);
			lines.push(`  ${f.name}: ${ts};`);
		}
		lines.push('}');
		lines.push('');
	}

	for (const t of allTypes) {
		if (t.kind !== 'UNION') continue;
		lines.push(`export type ${t.name} =`);
		for (const pt of t.possibleTypes || []) lines.push(`  | ${pt.name}`);
		lines.push(';');
		lines.push('');
	}

	return lines.join('\n');
}

async function run() {
	const { config } = await loadConfig(process.cwd());
	const codegen = config.codegen ?? config;

	const schemaDir = resolve(process.cwd(), codegen.schema?.dir ?? './schema');
	const typesDir = resolve(process.cwd(), codegen.types?.dir ?? './src/graphql/types');

	const filename = codegen.schema?.filename ?? 'schema.json';
	const schemaPath = join(schemaDir, filename);

	const autoDownloadSchema = codegen.schema?.autoDownloadSchema
		|| codegen.schema?.autoDownload
		|| codegen.schema?.autodownloadschema
		|| config.autoDownloadSchema
		|| config.autoDownload
		|| config.autodownloadschema;

	const shouldDownload = autoDownloadSchema || (!existsSync(schemaPath) && codegen.schema?.endpoint);

	if (shouldDownload && codegen.schema?.endpoint) {
		console.log(`Auto-downloading schema from ${codegen.schema.endpoint}...`);
		try {
			const { downloadAndStoreSchema } = await import('../projects/dumbql/downloader/src/public-api.ts');
			await downloadAndStoreSchema({
				endpoint: codegen.schema.endpoint,
				outputDir: schemaDir,
				filename: filename,
				headers: codegen.schema.headers,
			});
			console.log('Schema downloaded successfully.');
		} catch (err) {
			if (!existsSync(schemaPath)) {
				console.error(`Failed to auto-download schema: ${err.message}`);
				process.exit(1);
			} else {
				console.warn(`Warning: Failed to update schema, using cached version: ${err.message}`);
			}
		}
	} else if (!existsSync(schemaPath)) {
		console.error(`Schema not found at ${schemaPath}. Run \`npm run schema:download\` first.`);
		process.exit(1);
	}

	const schemaRaw = readFileSync(schemaPath, 'utf-8');
	const schemaData = JSON.parse(schemaRaw);

	if (!existsSync(typesDir)) mkdirSync(typesDir, { recursive: true });

	const typesCode = generate(schemaData.__schema || schemaData, config);
	const outputPath = join(typesDir, 'index.ts');
	writeFileSync(outputPath, typesCode);

	console.log(`Types generated: ${outputPath}`);
}

run();
